import { randomBytes } from 'node:crypto';
import { decrypt, encrypt, storedSecretNames, type AppSpec } from '@pupitre/core';
import { and, asc, eq, inArray } from 'drizzle-orm';
import { z } from 'zod';
import { getDb, type Database } from './client.js';
import { applicationSecrets } from './schema/secrets.js';

/**
 * Store of application secret values.
 *
 * Absolute rule, modeled on `targets.ts`: `encrypted_value` only leaves here
 * through `resolveApplicationSecrets()`, reserved to the worker. Every other read
 * goes through `publicColumns`, where the column simply does not exist — the
 * value therefore cannot leak by a forgotten filter in a handler.
 *
 * No function of this module returns a clear value to a human: there is no
 * "read a secret". One sets one, replaces it, regenerates it, deletes it. That
 * is all.
 */

const publicColumns = {
  id: applicationSecrets.id,
  applicationId: applicationSecrets.applicationId,
  name: applicationSecrets.name,
  origin: applicationSecrets.origin,
  createdAt: applicationSecrets.createdAt,
  updatedAt: applicationSecrets.updatedAt,
} as const;

export type SecretOrigin = 'generated' | 'provided';

/** A secret as the API is allowed to describe it. Without its value. */
export type PublicApplicationSecret = {
  id: string;
  applicationId: string;
  name: string;
  origin: SecretOrigin;
  createdAt: Date;
  updatedAt: Date;
};

/** The same grammar as `serviceSchema.secrets` in the AppSpec. */
export const secretNameSchema = z
  .string()
  .min(1)
  .max(128)
  .regex(/^[A-Z_][A-Z0-9_]*$/, 'nom en MAJUSCULES_AVEC_UNDERSCORES');

/**
 * Value entered by an operator.
 *
 * The minimum is deliberately `0`: some images tell "variable absent" from
 * "variable empty", and it is for the operator to decide. The render does not
 * confuse the two either — it fails on a secret *absent* from the store, never on
 * a deliberately empty secret.
 */
export const secretValueSchema = z.string().max(8192);

/** Entropy bytes of a generated value. 24 → 32 base64url characters. */
const GENERATED_SECRET_BYTES = 24;

/**
 * Value generated by the panel.
 *
 * base64url: the alphabet (`A-Za-z0-9-_`) goes without escaping through a
 * `.env`, a command line, a Kubernetes Secret's `stringData` and a `postgres://`
 * connection URL. A password that must be quoted somewhere always ends up badly
 * quoted somewhere.
 */
export function generateSecretValue(): string {
  return randomBytes(GENERATED_SECRET_BYTES).toString('base64url');
}

export async function listApplicationSecrets(
  applicationId: string,
  db: Database = getDb(),
): Promise<PublicApplicationSecret[]> {
  return db
    .select(publicColumns)
    .from(applicationSecrets)
    .where(eq(applicationSecrets.applicationId, applicationId))
    .orderBy(asc(applicationSecrets.name));
}

/**
 * Creates the declared secrets that do not exist yet, with a generated value.
 *
 * ── Generated by default, entered as an override ────────────────────────────
 *
 * The password GLPI uses to reach its database has no reason to be chosen by a
 * human: nobody ever types it, nobody ever reads it, and an operator asked for a
 * password writes a bad one. The panel draws it at random, strong, and that is
 * the end of it. An *external* secret — a third-party service's API key — cannot
 * be guessed: it is then entered, and `setApplicationSecret()` marks it
 * `provided`.
 *
 * Generating by default has a consequence we want: **no deployment can fail
 * anymore for not having filled in a secret**, which was exactly the original
 * failure. Input stays possible, it is never required.
 *
 * Idempotent: called at the application's creation, at each update of its
 * AppSpec, and one last time by the worker before the render — that third time
 * covers the applications created before the store existed.
 * `onConflictDoNothing` makes the unique constraint the arbiter, not an `if`.
 *
 * Returns the names really created, so that the caller can log them.
 */
export async function ensureApplicationSecrets(
  applicationId: string,
  names: readonly string[],
  db: Database = getDb(),
): Promise<string[]> {
  const wanted = [...new Set(names)];
  if (wanted.length === 0) return [];

  const created = await db
    .insert(applicationSecrets)
    .values(
      wanted.map((name) => ({
        applicationId,
        name,
        encryptedValue: encrypt(generateSecretValue()),
        origin: 'generated' as const,
      })),
    )
    .onConflictDoNothing({
      target: [applicationSecrets.applicationId, applicationSecrets.name],
    })
    .returning({ name: applicationSecrets.name });

  return created.map((row) => row.name);
}

/**
 * Names of an AppSpec's secrets that need a **value** in the store.
 *
 * The roots only. A secret that declares `from` reuses another's value: it has no
 * row of its own. Creating one would fall back on the original failure — two
 * independent random values for a single password — with one more step.
 */
export function declaredSecretsOf(spec: AppSpec): string[] {
  return storedSecretNames(spec);
}

/**
 * Aligns the store on the current AppSpec.
 *
 * ── What happens when the AppSpec changes ───────────────────────────────────
 *
 * An **added** secret is created on the fly, with a generated value: nothing to
 * do for the operator, the next deployment will find it.
 *
 * A **removed** secret is not deleted. A destroyed value does not come back, and
 * the data volume that uses it is still there: an AppSpec edited by hand then
 * corrected would have erased the password of a database still in service. The
 * row therefore stays, marked "no longer declared" by the screen, and only an
 * explicit deletion removes it. The only automatic erasure is the cascade when
 * the application itself disappears.
 */
export async function syncApplicationSecrets(
  applicationId: string,
  spec: AppSpec,
  db: Database = getDb(),
): Promise<string[]> {
  return ensureApplicationSecrets(applicationId, declaredSecretsOf(spec), db);
}

/** Sets or replaces a secret's value. Never returns the value. */
export async function setApplicationSecret(
  applicationId: string,
  name: string,
  value: string,
  origin: SecretOrigin = 'provided',
  db: Database = getDb(),
): Promise<PublicApplicationSecret> {
  const [row] = await db
    .insert(applicationSecrets)
    .values({ applicationId, name, encryptedValue: encrypt(value), origin })
    .onConflictDoUpdate({
      target: [applicationSecrets.applicationId, applicationSecrets.name],
      set: { encryptedValue: encrypt(value), origin, updatedAt: new Date() },
    })
    .returning(publicColumns);

  if (!row) throw new Error("setApplicationSecret: the write returned no row");
  return row;
}

/** Replaces the value with a new value drawn at random. */
export async function rotateApplicationSecret(
  applicationId: string,
  name: string,
  db: Database = getDb(),
): Promise<PublicApplicationSecret> {
  return setApplicationSecret(applicationId, name, generateSecretValue(), 'generated', db);
}

export async function deleteApplicationSecret(
  applicationId: string,
  name: string,
  db: Database = getDb(),
): Promise<boolean> {
  const [row] = await db
    .delete(applicationSecrets)
    .where(
      and(
        eq(applicationSecrets.applicationId, applicationId),
        eq(applicationSecrets.name, name),
      ),
    )
    .returning({ id: applicationSecrets.id });
  return row !== undefined;
}

/**
 * Decrypts the requested values. **Worker only.**
 * No HTTP route must call this function.
 *
 * A name absent from the store is absent from the result — it is not replaced by
 * an empty string. It is that distinction the render uses to fail by naming the
 * missing secret rather than writing a silent `.env`.
 */
export async function resolveApplicationSecrets(
  applicationId: string,
  names: readonly string[],
  db: Database = getDb(),
): Promise<Record<string, string>> {
  const wanted = [...new Set(names)];
  if (wanted.length === 0) return {};

  const rows = await db
    .select({ name: applicationSecrets.name, encryptedValue: applicationSecrets.encryptedValue })
    .from(applicationSecrets)
    .where(
      and(
        eq(applicationSecrets.applicationId, applicationId),
        inArray(applicationSecrets.name, wanted),
      ),
    );

  const values: Record<string, string> = {};
  for (const row of rows) values[row.name] = decrypt(row.encryptedValue);
  return values;
}
