/**
 * Writes `src/lib/mcp/route-table.ts`: every Route Handler of the panel, imported
 * statically, for the MCP endpoint to call them in-process.
 *
 * Why a generated file rather than a dynamic `import()`: the bundler must see
 * each module to put it in the server build. `test/mcp.test.mjs` fails as soon
 * as the table and `src/app/api` drift apart, and names this command.
 *
 *   pnpm --filter @pupitre/web routes:table
 */
import { readdirSync, statSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const webRoot = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const apiRoot = path.join(webRoot, 'src', 'app', 'api');
const target = path.join(webRoot, 'src', 'lib', 'mcp', 'route-table.ts');

/** Kept out of the table, with the reason. Read by the test too. */
export const EXCLUDED_ROUTES = {
  '/api/auth/[...all]': 'Better Auth: sign-in flows, driven by a browser',
  '/api/integrations/github/callback': 'a browser round trip from github.com',
  '/api/mcp': 'the MCP endpoint itself',
  '/api/realtime': 'the screens’ signal stream (SSE), never read to its end',
};

export function apiPatterns() {
  const found = [];
  const walk = (dir) => {
    for (const name of readdirSync(dir).sort()) {
      const full = path.join(dir, name);
      if (statSync(full).isDirectory()) walk(full);
      else if (name === 'route.ts') {
        const relative = path.relative(apiRoot, path.dirname(full)).split(path.sep).join('/');
        found.push(relative === '' ? '/api' : `/api/${relative}`);
      }
    }
  };
  walk(apiRoot);
  return found.sort();
}

function identifier(pattern) {
  return `route_${pattern
    .replace(/^\/api\/?/, '')
    .replace(/\[([^\]]+)\]/g, '$$$1')
    .replace(/[^A-Za-z0-9$]+/g, '_')}`;
}

export function renderTable() {
  const patterns = apiPatterns().filter((pattern) => !(pattern in EXCLUDED_ROUTES));
  const imports = patterns.map(
    (pattern) => `import * as ${identifier(pattern)} from '@/app${pattern}/route';`,
  );
  const entries = patterns.map((pattern) => `  '${pattern}': ${identifier(pattern)},`);
  return `// Generated by \`pnpm --filter @pupitre/web routes:table\` — do not edit by hand.
import 'server-only';
${imports.join('\n')}

/**
 * Every Route Handler the MCP endpoint can reach, by its pattern. Those set aside
 * are listed in \`scripts/route-table.mjs\`, with the reason.
 */
export const ROUTE_MODULES: Record<string, object> = {
${entries.join('\n')}
};
`;
}

if (process.argv[1] && fileURLToPath(import.meta.url) === path.resolve(process.argv[1])) {
  writeFileSync(target, renderTable());
  console.log(`wrote ${path.relative(webRoot, target)}`);
}
