import { stringify } from 'yaml';
import { acmeDirectory, type AcmeSettings } from '../model.js';

/**
 * What Pupitre sets up when asked to install Traefik — pure rendering, applied
 * by the provider.
 *
 * ── In a container ──────────────────────────────────────────────────────────
 * A `pupitre-proxy` Compose project, on the host network: Traefik listens
 * directly on 80 and 443, and reaches the applications on `127.0.0.1:{port}` —
 * which lets their port not be open to the world. Neither a mounted Docker
 * socket nor a dashboard: it only reads the folder where Pupitre places the
 * routes, read-only. The certificates live in a volume.
 *
 * ── In K3s ──────────────────────────────────────────────────────────────────
 * K3s already ships Traefik. We do not replace it, we configure it through a
 * `HelmChartConfig`: an ACME resolver and a volume for the certificates. If
 * someone already wrote theirs, Pupitre does not overwrite it.
 */

/** Pinned version: the 3.7 series, patch updates included. */
export const TRAEFIK_IMAGE = 'traefik:v3.7';
export const MANAGED_PROJECT = 'pupitre-proxy';
export const MANAGED_CONTAINER = 'pupitre-traefik';
export const MANAGED_RESOLVER = 'pupitre';
/** The liveness probe's entry point, on loopback only. */
export const PING_ADDRESS = '127.0.0.1:8082';
export const MANAGED_ANNOTATION = 'pupitre.io/managed-by';

/** The proxy's folder on the machine: `{driver root}/proxy`. */
export function proxyRoot(rootPath: string): string {
  return `${rootPath.replace(/\/+$/, '')}/proxy`;
}

export function defaultDynamicDirectory(rootPath: string): string {
  return `${proxyRoot(rootPath)}/dynamic`;
}

function acmeArguments(acme: AcmeSettings, storage: string): string[] {
  const resolver = `--certificatesresolvers.${MANAGED_RESOLVER}.acme`;
  return [
    `${resolver}.email=${acme.email}`,
    `${resolver}.storage=${storage}`,
    `${resolver}.httpchallenge.entrypoint=web`,
    `${resolver}.caserver=${acmeDirectory(acme)}`,
  ];
}

const HEALTHCHECK = [
  'CMD',
  'traefik',
  'healthcheck',
  '--ping',
  '--ping.entrypoint=ping',
  `--entrypoints.ping.address=${PING_ADDRESS}`,
];

export function renderManagedCompose(rootPath: string, acme: AcmeSettings): string {
  const root = proxyRoot(rootPath);
  const ca = acme.caCertificate !== null;
  const document = {
    name: MANAGED_PROJECT,
    services: {
      traefik: {
        image: TRAEFIK_IMAGE,
        container_name: MANAGED_CONTAINER,
        restart: 'unless-stopped',
        network_mode: 'host',
        security_opt: ['no-new-privileges:true'],
        command: [
          '--entrypoints.web.address=:80',
          '--entrypoints.websecure.address=:443',
          `--entrypoints.ping.address=${PING_ADDRESS}`,
          '--ping=true',
          '--ping.entrypoint=ping',
          '--providers.file.directory=/etc/traefik/dynamic',
          '--providers.file.watch=true',
          ...acmeArguments(acme, '/data/acme.json'),
          '--log.level=INFO',
          '--global.checknewversion=false',
          '--global.sendanonymoususage=false',
        ],
        ...(ca ? { environment: { LEGO_CA_CERTIFICATES: '/etc/traefik/acme-ca.pem' } } : {}),
        volumes: [
          `${root}/dynamic:/etc/traefik/dynamic:ro`,
          ...(ca ? [`${root}/acme-ca.pem:/etc/traefik/acme-ca.pem:ro`] : []),
          'acme:/data',
        ],
        labels: {
          'pupitre.managed-by': 'pupitre',
          'pupitre.role': 'proxy',
        },
        healthcheck: {
          test: HEALTHCHECK,
          interval: '10s',
          timeout: '5s',
          retries: 3,
          start_period: '10s',
        },
      },
    },
    volumes: { acme: { name: `${MANAGED_PROJECT}-acme` } },
  };
  return `# Generated by Pupitre — this machine's reverse proxy.\n${stringify(document, { lineWidth: 0 })}`;
}

export const CA_CONFIGMAP = 'pupitre-acme-ca';

export function renderHelmChartConfig(namespace: string, acme: AcmeSettings): string {
  const ca = acme.caCertificate !== null;
  const values = {
    additionalArguments: acmeArguments(acme, '/data/acme.json'),
    persistence: { enabled: true },
    ...(ca
      ? {
          env: [{ name: 'LEGO_CA_CERTIFICATES', value: '/pupitre-acme-ca/ca.pem' }],
          volumes: [{ name: CA_CONFIGMAP, mountPath: '/pupitre-acme-ca', type: 'configMap' }],
        }
      : {}),
  };
  const objects: unknown[] = [];
  if (ca) {
    objects.push({
      apiVersion: 'v1',
      kind: 'ConfigMap',
      metadata: { name: CA_CONFIGMAP, namespace, annotations: { [MANAGED_ANNOTATION]: 'pupitre' } },
      data: { 'ca.pem': acme.caCertificate },
    });
  }
  objects.push({
    apiVersion: 'helm.cattle.io/v1',
    kind: 'HelmChartConfig',
    metadata: { name: 'traefik', namespace, annotations: { [MANAGED_ANNOTATION]: 'pupitre' } },
    spec: { valuesContent: stringify(values, { lineWidth: 0, version: '1.1' }) },
  });
  // YAML 1.1, like everything going to the Kubernetes API: see `serializeKubeObjects`.
  return objects.map((object) => stringify(object, { lineWidth: 0, version: '1.1' })).join('---\n');
}
