import { stringify } from 'yaml';
import type { TraefikFileConfig, TraefikKubernetesConfig } from './config.js';
import type { ProxyRoute } from '../types.js';

/**
 * What Pupitre places at Traefik, without side effects: a dynamic configuration
 * file (`file` mode) or Kubernetes objects (`kubernetes` mode). Tested
 * separately, like the drivers' renders.
 *
 * Per domain, two routers at most: one on the HTTPS entry point, with the
 * certificate resolver; the other on HTTP, which serves or redirects to HTTPS.
 * The names are prefixed by the application: two applications cannot step on
 * each other, and what Pupitre did not set up does not carry that prefix.
 */

export const ROUTE_MARK = 'Generated by Pupitre';

/** `blog.example.com` → `blog-example-com`: a router name fragment. */
function hostKey(hostname: string): string {
  return hostname.replace(/[^a-z0-9]+/g, '-');
}

function hostRule(hostnames: string[]): string {
  return hostnames.map((host) => `Host(\`${host}\`)`).join(' || ');
}

type RouterPlan = { https: ProxyRoute[]; redirect: ProxyRoute[]; plain: ProxyRoute[] };

/**
 * Who goes where. An HTTPS route without an HTTPS entry point is served over
 * HTTP: the proxy cannot do better, and the screen will not have offered it
 * anyway.
 */
export function planRouters(routes: ProxyRoute[], httpsEntryPoint: string | null): RouterPlan {
  const plan: RouterPlan = { https: [], redirect: [], plain: [] };
  for (const route of routes) {
    if (route.tls && httpsEntryPoint) {
      plan.https.push(route);
      (route.redirectHttps ? plan.redirect : plan.plain).push(route);
    } else {
      plan.plain.push(route);
    }
  }
  return plan;
}

// ─── mode file ───────────────────────────────────────────────────────────────

export function traefikFileName(appSlug: string): string {
  return `${appSlug}.yml`;
}

export function renderTraefikFile(
  appSlug: string,
  routes: ProxyRoute[],
  upstreamUrl: string,
  config: TraefikFileConfig,
): string {
  const plan = planRouters(routes, config.entryPoints.https);
  const service = appSlug;
  const redirect = `${appSlug}-redirect-https`;
  const routers: Record<string, unknown> = {};

  for (const route of plan.https) {
    routers[`${appSlug}--${hostKey(route.hostname)}`] = {
      rule: hostRule([route.hostname]),
      entryPoints: [config.entryPoints.https],
      service,
      tls: config.certResolver ? { certResolver: config.certResolver } : {},
    };
  }
  for (const route of plan.redirect) {
    routers[`${appSlug}--${hostKey(route.hostname)}--http`] = {
      rule: hostRule([route.hostname]),
      entryPoints: [config.entryPoints.http],
      middlewares: [redirect],
      service,
    };
  }
  for (const route of plan.plain) {
    routers[`${appSlug}--${hostKey(route.hostname)}--http`] = {
      rule: hostRule([route.hostname]),
      entryPoints: [config.entryPoints.http],
      service,
    };
  }

  const document = {
    http: {
      routers,
      ...(plan.redirect.length > 0
        ? { middlewares: { [redirect]: { redirectScheme: { scheme: 'https', permanent: true } } } }
        : {}),
      services: { [service]: { loadBalancer: { servers: [{ url: upstreamUrl }] } } },
    },
  };
  return (
    `# ${ROUTE_MARK} for "${appSlug}" — do not edit: the file is rewritten at each deployment.\n` +
    stringify(document, { lineWidth: 0 })
  );
}

// ─── mode kubernetes ─────────────────────────────────────────────────────────

/** The labels that say "set up by Pupitre, for this application". */
export function routeLabels(appSlug: string): Record<string, string> {
  return {
    'app.kubernetes.io/managed-by': 'pupitre',
    'app.kubernetes.io/part-of': appSlug,
    'pupitre.io/role': 'route',
  };
}

/**
 * The names of an application's Ingresses. `{slug}` reuses the one the K3s
 * driver set before routes went through the proxy: applying it replaces it
 * instead of leaving a second one on the same domain.
 */
export function ingressNames(appSlug: string): { https: string; redirect: string; plain: string } {
  return { https: appSlug, redirect: `${appSlug}-redirect`, plain: `${appSlug}-http` };
}

export const REDIRECT_MIDDLEWARE = 'pupitre-redirect-https';

type KubeObject = {
  apiVersion: string;
  kind: string;
  metadata: {
    name: string;
    namespace?: string;
    labels: Record<string, string>;
    annotations?: Record<string, string>;
  };
  spec: Record<string, unknown>;
};

export type TraefikKubernetesRender = {
  objects: KubeObject[];
  /** The application's Ingresses to remove: expected by the naming, absent from this render. */
  stale: string[];
};

export function renderTraefikIngresses(
  appSlug: string,
  routes: ProxyRoute[],
  upstream: { namespace: string; service: string; port: number },
  config: TraefikKubernetesConfig,
): TraefikKubernetesRender {
  const plan = planRouters(routes, config.entryPoints.https);
  const names = ingressNames(appSlug);
  const labels = routeLabels(appSlug);
  const objects: KubeObject[] = [];

  const ingress = (name: string, hosts: ProxyRoute[], annotations: Record<string, string>) => {
    objects.push({
      apiVersion: 'networking.k8s.io/v1',
      kind: 'Ingress',
      metadata: { name, namespace: upstream.namespace, labels, annotations },
      spec: {
        ingressClassName: config.ingressClass,
        rules: hosts.map((route) => ({
          host: route.hostname,
          http: {
            paths: [
              {
                path: '/',
                pathType: 'Prefix',
                backend: { service: { name: upstream.service, port: { number: upstream.port } } },
              },
            ],
          },
        })),
      },
    });
  };

  if (plan.https.length > 0 && config.entryPoints.https) {
    ingress(names.https, plan.https, {
      'traefik.ingress.kubernetes.io/router.entrypoints': config.entryPoints.https,
      'traefik.ingress.kubernetes.io/router.tls': 'true',
      ...(config.certResolver
        ? { 'traefik.ingress.kubernetes.io/router.tls.certresolver': config.certResolver }
        : {}),
    });
  }
  if (plan.redirect.length > 0) {
    objects.push({
      apiVersion: 'traefik.io/v1alpha1',
      kind: 'Middleware',
      metadata: { name: REDIRECT_MIDDLEWARE, namespace: upstream.namespace, labels },
      spec: { redirectScheme: { scheme: 'https', permanent: true } },
    });
    ingress(names.redirect, plan.redirect, {
      'traefik.ingress.kubernetes.io/router.entrypoints': config.entryPoints.http,
      'traefik.ingress.kubernetes.io/router.middlewares': `${upstream.namespace}-${REDIRECT_MIDDLEWARE}@kubernetescrd`,
    });
  }
  if (plan.plain.length > 0) {
    ingress(names.plain, plan.plain, {
      'traefik.ingress.kubernetes.io/router.entrypoints': config.entryPoints.http,
    });
  }

  const kept = new Set(
    objects.filter((object) => object.kind === 'Ingress').map((o) => o.metadata.name),
  );
  return { objects, stale: Object.values(names).filter((name) => !kept.has(name)) };
}

/**
 * In YAML 1.1, like the K3s driver's manifests: the Kubernetes API reads with a
 * 1.1 parser, where `on` or `y` are booleans — 1.1 serialization puts quotes
 * where they are needed.
 */
export function serializeKubeObjects(objects: KubeObject[]): string {
  return objects.map((object) => stringify(object, { lineWidth: 0, version: '1.1' })).join('---\n');
}

// ─── a machine outside the cluster ───────────────────────────────────────────

/**
 * The namespace of routes to machines outside the cluster: the application does
 * not run there, so it has no namespace of its own here.
 */
export const REMOTE_NAMESPACE = 'pupitre-routes';

/**
 * A cluster's Traefik serving a machine **outside** the cluster — the central
 * proxy. An Ingress only targets a Service: we give it one without a selector,
 * whose only endpoint is the other machine's address (EndpointSlice). Neither
 * `ExternalName`, which Traefik refuses by default, nor a proxy setting to
 * change.
 */
export function renderTraefikRemoteIngresses(
  name: string,
  routes: ProxyRoute[],
  upstream: { host: string; port: number },
  config: TraefikKubernetesConfig,
): TraefikKubernetesRender {
  const labels = routeLabels(name);
  const rendered = renderTraefikIngresses(
    name,
    routes,
    { namespace: REMOTE_NAMESPACE, service: name, port: upstream.port },
    config,
  );
  const backing: KubeObject[] = [
    {
      apiVersion: 'v1',
      kind: 'Namespace',
      metadata: { name: REMOTE_NAMESPACE, labels: { 'app.kubernetes.io/managed-by': 'pupitre' } },
      spec: {},
    },
    {
      apiVersion: 'v1',
      kind: 'Service',
      metadata: { name, namespace: REMOTE_NAMESPACE, labels },
      spec: {
        ports: [{ name: 'http', port: upstream.port, targetPort: upstream.port, protocol: 'TCP' }],
      },
    },
    {
      apiVersion: 'discovery.k8s.io/v1',
      kind: 'EndpointSlice',
      metadata: {
        name: `${name}-upstream`,
        namespace: REMOTE_NAMESPACE,
        labels: { ...labels, 'kubernetes.io/service-name': name },
      },
      // An EndpointSlice has no `spec`: its fields are at the root.
      addressType: 'IPv4',
      endpoints: [{ addresses: [upstream.host], conditions: { ready: true } }],
      ports: [{ name: 'http', port: upstream.port, protocol: 'TCP' }],
    } as unknown as KubeObject,
  ];
  return { objects: [...backing, ...rendered.objects], stale: rendered.stale };
}
