-- Les runs déjà en base sont numérotés dans l'ordre où ils ont été créés.
-- Ajouter directement une colonne identité les numéroterait dans l'ordre
-- physique de la table, qui ne veut rien dire.
ALTER TABLE "deployments" ADD COLUMN "number" integer;--> statement-breakpoint
UPDATE "deployments" AS d SET "number" = o.n FROM (SELECT "id", row_number() OVER (ORDER BY "created_at", "id") AS n FROM "deployments") AS o WHERE d."id" = o."id";--> statement-breakpoint
ALTER TABLE "deployments" ALTER COLUMN "number" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "deployments" ALTER COLUMN "number" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "deployments_number_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
SELECT setval('"deployments_number_seq"', (SELECT COALESCE(MAX("number"), 0) + 1 FROM "deployments"), false);--> statement-breakpoint
CREATE UNIQUE INDEX "deployments_number_idx" ON "deployments" USING btree ("number");
