import { index, pgTable, text, timestamp, uniqueIndex, uuid } from 'drizzle-orm/pg-core';
import { secretOriginEnum } from '../enums.js';
import { applications } from './infra.js';

/**
 * Store of secret values.
 *
 * The AppSpec only declares **names** (`secrets: ["POSTGRES_PASSWORD"]`): that is
 * what lets it be read, versioned and regenerated by the AI without ever carrying
 * a clear value. The values live here, encrypted, and are only decrypted at
 * render time, by the worker.
 *
 * ── Why the value is attached to the APPLICATION, not the deployment ────────
 *
 * It is this table's structuring decision, and the one nobody would find again
 * six months later.
 *
 * A database password is not a property of going live, it is a property of the
 * application: the `/var/lib/postgresql` volume outlives the deployment that
 * created it and carries the password of the **first** start. Attaching the
 * secret to the deployment, or drawing it at random at each render, would
 * produce a different `.env` at each release: PostgreSQL would refuse the
 * connection with the new password on the old volume, and the application would
 * go down at the second deployment — that is at the worst moment, the one where
 * one believes nothing changed.
 *
 * Attached to the application, the value is **stable over time**: it is created
 * once, reused at each deployment, on each target and on each runtime. It only
 * changes if someone explicitly asks for it.
 *
 * ── What is never done ──────────────────────────────────────────────────────
 *
 * This table is never read by a route answering a human. The only decryption
 * path is `resolveApplicationSecrets()`, reserved to the worker, exactly like
 * `getTargetSecret()` for SSH credentials.
 */
export const applicationSecrets = pgTable(
  'application_secrets',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    applicationId: uuid('application_id')
      .notNull()
      .references(() => applications.id, { onDelete: 'cascade' }),
    /** Name declared by the AppSpec: `^[A-Z_][A-Z0-9_]*$`. */
    name: text('name').notNull(),
    /**
     * AES-256-GCM under `MASTER_KEY`, `version:iv:authTag:ciphertext` format — the
     * same envelope as `targets.encrypted_credential`, the same helper
     * (`@pupitre/core` › `encrypt()` / `decrypt()`), the same rule: never returned by
     * the API, never logged.
     */
    encryptedValue: text('encrypted_value').notNull(),
    origin: secretOriginEnum('origin').notNull().default('generated'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    // One name, one value, per application. The database imposes it: without this
    // constraint, two concurrent deployments of the same application could each
    // generate "their" password, and the last one written would silently win.
    uniqueIndex('application_secrets_app_name_idx').on(t.applicationId, t.name),
    index('application_secrets_application_id_idx').on(t.applicationId),
  ],
);
