#!/usr/bin/env bash
#
# Checks the secret values store and the drivers' probe rule:
#
#   1. a two-service application — PostgreSQL not exposed, a console that
#      depends on it — deploys, healthy, database initialized
#   2. the `.env` placed on the target carries a NON-EMPTY value, generated by
#      the panel without anyone typing it
#   3. a REDEPLOYMENT reuses the same secret, and the database still answers
#   4. the value comes out neither through the API, nor in the HTML, nor in
#      `audit_logs`, nor in the panel's and the worker's logs
#   5. a declared secret that cannot be resolved makes the RENDERING fail, with
#      a message that names it — and a deliberately empty secret stays accepted
#   6. the non-exposed database gets a TCP probe, not an HTTP probe
#   7. a typed secret can be replaced; there is no way to read it back
#
# Then the ALIASES — a password that two images read under two names:
#
#   8. an OLD AppSpec, `secrets: ["NAME"]` as bare strings, still reads and
#      deploys (it is scenario 1 to 7: it was not rewritten)
#   9. two names linked through `from` get the SAME value in the placed `.env`
#      — comparison of SHA-256 fingerprints, never a printed value
#  10. a SINGLE row in the database for both names; the alias does not create one
#  11. an alias to a non-existent secret is refused at the AppSpec's
#      VALIDATION, naming it, and an alias cycle is too
#  12. a MariaDB database STARTS and WordPress CONNECTS to it for real — the
#      authentication succeeds, it is the only test that matters
#  13. the K3s rendering gets the same complete map as the Docker rendering
#
# The target used is `cible-de-verification` (docker-in-docker), never a
# production machine. Everything the script creates is destroyed at the end.
#
# Usage:
#   ./scripts/verify-secrets.sh
#   BASE_URL=http://localhost:3200 TARGET_NAME=my-vm ./scripts/verify-secrets.sh
#
set -euo pipefail

BASE_URL="${BASE_URL:-http://localhost:3000}"
ADMIN_EMAIL="${ADMIN_EMAIL:-admin@example.test}"
ADMIN_PASSWORD="${ADMIN_PASSWORD:-motdepasse-tres-long}"
TARGET_NAME="${TARGET_NAME:-cible-de-verification}"
CLIENT_IP="${CLIENT_IP:-198.51.100.77}"
SLUG="${SLUG:-verif-secrets}"
SLUG_ALIAS="${SLUG_ALIAS:-verif-alias}"
DEPLOY_TIMEOUT="${DEPLOY_TIMEOUT:-600}"

# SSH access to the target, to read what was really placed there.
SSH_KEY="${SSH_KEY:-.test-target-key}"
SSH_HOST="${SSH_HOST:-127.0.0.1}"
SSH_PORT="${SSH_PORT:-2222}"
SSH_USER="${SSH_USER:-tp}"
DRIVER_ROOT_PATH="${DRIVER_ROOT_PATH:-/opt/bootstrap}"

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
WORK="$(mktemp -d)"
JAR="$WORK/admin.jar"
BODY="$WORK/body.json"
trap 'rm -rf "$WORK"' EXIT

command -v jq >/dev/null || { echo "jq is required"; exit 1; }

pass() { printf '  \033[32m✓\033[0m %s\n' "$1"; }
fail() { printf '  \033[31m✗\033[0m %s\n' "$1"; exit 1; }
step() { printf '\n\033[1m%s\033[0m\n' "$1"; }
info() { printf '    \033[2m%s\033[0m\n' "$1"; }

req() {
  local method="$1" path="$2" data="${3:-}"
  local args=(-s -o "$BODY" -w '%{http_code}' -X "$method" "$BASE_URL$path"
              -H 'content-type: application/json' -H "origin: $BASE_URL"
              -H "x-forwarded-for: $CLIENT_IP" -b "$JAR" -c "$JAR")
  [ -n "$data" ] && args+=(--data-binary "$data")
  curl "${args[@]}"
}

psql_q() { docker compose exec -T postgres psql -U tp -d tp -tAc "$1"; }

# Runs on the TARGET. The script reads files placed over there, but never
# prints their content: only lengths and fingerprints.
on_target() {
  ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
      -o LogLevel=ERROR -i "$ROOT/$SSH_KEY" -p "$SSH_PORT" \
      "$SSH_USER@$SSH_HOST" "$@"
}

login() {
  local code
  for _ in 1 2 3 4 5; do
    code=$(req POST /api/auth/sign-in/email \
      "{\"email\":\"$ADMIN_EMAIL\",\"password\":\"$ADMIN_PASSWORD\"}")
    case "$code" in
      200) assert_admin; return 0 ;;
      429) sleep 6 ;;
      *)   break ;;
    esac
  done
  code=$(req POST /api/auth/sign-up/email \
    "{\"name\":\"Admin\",\"email\":\"$ADMIN_EMAIL\",\"password\":\"$ADMIN_PASSWORD\"}")
  [ "$code" = "200" ] || fail "sign-in failed (HTTP $code): $(cat "$BODY")"
  assert_admin
}

# The account must be an administrator. Settling for a successful sign-in would
# let the script fail much further, on a cryptic 403.
assert_admin() {
  local role
  role=$(jq -r '.user.role // empty' "$BODY")
  [ "$role" = "admin" ] && return 0
  fail "\"$ADMIN_EMAIL\" has the role \"${role:-none}\", not \"admin\" — see /admin/users"
}

# Queues a deployment and waits for its terminal state. Identifier on stdout.
deploy() {
  local app="${1:-$APP_ID}"
  local code deploy_id status waited=0

  code=$(req POST /api/deployments "$(jq -nc \
    --arg app "$app" --arg target "$TARGET_ID" \
    '{applicationId:$app, targetId:$target, runtime:"docker", proxy:"traefik",
      autoRollback:false, scanConfig:{scanners:[], failOn:"NONE"}}')")
  [ "$code" = "202" ] || fail "POST /api/deployments → HTTP $code: $(cat "$BODY")"

  deploy_id=$(jq -r .id "$BODY")
  info "deployment $deploy_id queued" >&2

  while [ "$waited" -lt "$DEPLOY_TIMEOUT" ]; do
    sleep 5
    waited=$(( waited + 5 ))
    req GET "/api/deployments/$deploy_id" >/dev/null
    status=$(jq -r .status "$BODY")
    case "$status" in
      success|failed|rolled_back|destroyed) printf '%s' "$deploy_id"; return 0 ;;
    esac
  done
  fail "deployment $deploy_id did not complete in ${DEPLOY_TIMEOUT}s (state \"$status\")"
}

destroy() {
  local id="$1" code status waited=0
  code=$(req DELETE "/api/deployments/$id")
  case "$code" in
    202) ;;
    409|404) return 0 ;;
    *) info "DELETE /api/deployments/$id → HTTP $code"; return 0 ;;
  esac
  while [ "$waited" -lt 180 ]; do
    sleep 4
    waited=$(( waited + 4 ))
    req GET "/api/deployments/$id" >/dev/null
    status=$(jq -r .status "$BODY")
    [ "$status" = "destroyed" ] && return 0
  done
  info "deployment $id did not go to \"destroyed\" in 180s"
}

# ─── Cleanup, run on failure too ─────────────────────────────────────────────
# Destroys all the deployments of an application, then the application.
remove_app() {
  local app="$1" slug="$2" code ids rows
  req GET "/api/deployments?applicationId=$app&pageSize=50" >/dev/null 2>&1 || true
  ids=$(jq -r '.items[]?.id' "$BODY" 2>/dev/null || true)
  for id in $ids; do destroy "$id"; done
  # Destroying takes the application down on the target; purging erases the
  # trace in the database. Both are needed: `countDeploymentsFor()` counts all
  # the rows, destroyed ones included, and would refuse the application's
  # deletion.
  for id in $ids; do req DELETE "/api/deployments/$id/purge" >/dev/null 2>&1 || true; done
  code=$(req DELETE "/api/applications/$app")
  case "$code" in
    200) pass "application \"$slug\" deleted (secrets erased in cascade)" ;;
    *)   info "DELETE /api/applications/$app → HTTP $code: $(cat "$BODY")" ;;
  esac
  rows=$(psql_q "select count(*) from application_secrets where application_id = '$app';")
  [ "$rows" = "0" ] && pass "\"$slug\": no row left in application_secrets" \
                    || fail "$rows secret(s) survive the deletion of \"$slug\""
  on_target "test ! -d $DRIVER_ROOT_PATH/apps/$slug" >/dev/null 2>&1 \
    && pass "\"$slug\": release directory removed from the target" \
    || info "the $DRIVER_ROOT_PATH/apps/$slug directory still exists on the target"
}

CLEANED=0
cleanup() {
  [ "$CLEANED" = "1" ] && return 0
  CLEANED=1
  [ -n "${APP_ID:-}${ALIAS_APP_ID:-}" ] || return 0
  printf '\n\033[1m%s\033[0m\n' "Cleanup"
  if [ -n "${ALIAS_APP_ID:-}" ]; then remove_app "$ALIAS_APP_ID" "$SLUG_ALIAS"; fi
  if [ -n "${APP_ID:-}" ]; then remove_app "$APP_ID" "$SLUG"; fi
  return 0
}
trap 'cleanup; rm -rf "$WORK"' EXIT

# Deletes what a previous run may have left under this slug.
purge_previous() {
  local slug="$1" old
  req GET /api/applications >/dev/null
  old=$(jq -r --arg s "$slug" '.items[] | select(.slug == $s) | .id' "$BODY")
  [ -n "$old" ] || return 0
  req GET "/api/deployments?applicationId=$old&pageSize=50" >/dev/null
  local ids
  ids=$(jq -r '.items[]?.id' "$BODY")
  for id in $ids; do destroy "$id"; done
  for id in $ids; do req DELETE "/api/deployments/$id/purge" >/dev/null 2>&1 || true; done
  req DELETE "/api/applications/$old" >/dev/null
  info "application \"$slug\" from a previous run deleted"
}

# ─────────────────────────────────────────────────────────────────────────────

step "1. Sign-in"
login
pass "signed in as $ADMIN_EMAIL"

step "2. Verification target"
req GET /api/targets >/dev/null
TARGET_ID=$(jq -r --arg n "$TARGET_NAME" '.items[] | select(.name == $n) | .id' "$BODY")
[ -n "$TARGET_ID" ] || fail "target \"$TARGET_NAME\" not found — run ./scripts/setup-test-target.sh"
jq -e --arg n "$TARGET_NAME" \
  '.items[] | select(.name == $n) | .runtimesAvailable.docker.available == true' "$BODY" >/dev/null \
  || fail "the target \"$TARGET_NAME\" has no Docker runtime — run a preflight"
pass "target \"$TARGET_NAME\" ($TARGET_ID), Docker runtime available"
on_target 'echo ok' >/dev/null 2>&1 || fail "SSH to the target failed ($SSH_USER@$SSH_HOST:$SSH_PORT)"
pass "SSH to the target working"

step "3. Two-service application"
# `postgres:16` is the DEBIAN image, chosen on purpose: it ships neither `nc`,
# nor `wget`, nor `curl`. It is the one that made the Docker driver's TCP probe
# fail, and so kept `depends_on: service_healthy` waiting forever.
cat > "$WORK/spec.json" <<JSON
{
  "name": "$SLUG",
  "version": "1.0.0",
  "services": [
    {
      "name": "db",
      "source": { "type": "image", "ref": "postgres:16" },
      "port": 5432,
      "exposed": false,
      "env": { "POSTGRES_DB": "verifdb", "POSTGRES_USER": "verif" },
      "secrets": ["POSTGRES_PASSWORD"],
      "resources": { "cpuMilli": 1000, "memoryMi": 1024 },
      "healthcheck": { "path": "/", "port": 5432, "intervalSec": 5, "timeoutSec": 3, "retries": 40 },
      "volumes": [{ "name": "data", "mountPath": "/var/lib/postgresql/data", "size": "1Gi" }],
      "dependsOn": []
    },
    {
      "name": "console",
      "source": { "type": "image", "ref": "sosedoff/pgweb:0.16.2" },
      "port": 8081,
      "exposed": true,
      "env": {
        "PGHOST": "db", "PGPORT": "5432", "PGUSER": "verif",
        "PGDATABASE": "verifdb", "PGSSLMODE": "disable"
      },
      "secrets": ["POSTGRES_PASSWORD", "CONSOLE_API_TOKEN"],
      "resources": { "cpuMilli": 500, "memoryMi": 256 },
      "healthcheck": { "path": "/", "intervalSec": 5, "timeoutSec": 3, "retries": 30 },
      "dependsOn": ["db"]
    }
  ]
}
JSON

# Cleanup from a previous run.
purge_previous "$SLUG"
purge_previous "$SLUG_ALIAS"

jq '{appSpec: .}' "$WORK/spec.json" > "$WORK/create.json"
code=$(req POST /api/applications "@$WORK/create.json")
[ "$code" = "201" ] || fail "POST /api/applications → HTTP $code: $(cat "$BODY")"
APP_ID=$(jq -r .id "$BODY")
pass "application \"$SLUG\" created ($APP_ID)"

step "4. The declared secrets are generated, not asked for"
code=$(req GET "/api/applications/$APP_ID/secrets")
[ "$code" = "200" ] || fail "GET .../secrets → HTTP $code: $(cat "$BODY")"
jq -e '[.items[] | select(.isSet)] | length == 2' "$BODY" >/dev/null \
  || fail "two defined secrets expected, got $(jq -c '[.items[].name]' "$BODY")"
jq -e '.items[] | select(.name == "POSTGRES_PASSWORD") | .origin == "generated"' "$BODY" >/dev/null \
  || fail "POSTGRES_PASSWORD is not marked \"generated\""
jq -e '[.items[] | select(.name == "POSTGRES_PASSWORD") | .services] | flatten | sort == ["console","db"]' \
  "$BODY" >/dev/null || fail "POSTGRES_PASSWORD should be claimed by db AND console"
pass "$(jq -r '[.items[] | "\(.name) (\(.origin))"] | join(", ")' "$BODY")"

# Nothing in this response looks like a value.
jq -e '[.items[] | keys] | flatten | unique | index("value") == null' "$BODY" >/dev/null \
  || fail "the API's response carries a \"value\" field"
pass "no \"value\" field in the API's response"

step "5. An external secret is TYPED, and replaced"
TOKEN="jeton-externe-de-verification-8f3a2b"
code=$(req PUT "/api/applications/$APP_ID/secrets/CONSOLE_API_TOKEN" \
  "{\"value\":\"$TOKEN\"}")
[ "$code" = "200" ] || fail "PUT .../CONSOLE_API_TOKEN → HTTP $code: $(cat "$BODY")"
jq -e '.origin == "provided" and .isSet == true' "$BODY" >/dev/null \
  || fail "the typed secret is not marked \"provided\""
grep -q "$TOKEN" "$BODY" && fail "the PUT's response returns the typed value"
pass "CONSOLE_API_TOKEN typed → origin \"provided\", response without the value"

# There is no GET that returns the value.
req GET "/api/applications/$APP_ID/secrets" >/dev/null
grep -q "$TOKEN" "$BODY" && fail "the secrets list contains the typed value"
pass "no route returns the value — a secret is set, it is not read"

step "6. First deployment"
D1=$(deploy)
req GET "/api/deployments/$D1" >/dev/null
STATUS=$(jq -r .status "$BODY")
[ "$STATUS" = "success" ] || {
  info "steps: $(jq -rc '[.steps[] | "\(.key)=\(.status)"] | join(" ")' "$BODY")"
  info "error: $(jq -r '.error // "(none)"' "$BODY")"
  fail "the deployment ended as \"$STATUS\""
}
PORT=$(jq -r '.publishedPort // empty' "$BODY")
pass "deployment $D1 succeeded — published port $PORT"
jq -e '[.steps[] | select(.status == "failed")] | length == 0' "$BODY" >/dev/null \
  || fail "some steps failed"
pass "all the steps: $(jq -rc '[.steps[] | "\(.key)=\(.status)"] | join(" ")' "$BODY")"

step "7. Healthy containers, database initialized"
PS=$(on_target "docker ps --filter label=tp.app=$SLUG --format '{{.Names}} {{.Status}}'")
printf '%s\n' "$PS" | while IFS= read -r line; do [ -n "$line" ] && info "$line"; done
printf '%s' "$PS" | grep -q 'app-'"$SLUG"'-db-1 .*healthy' \
  || fail "the database container is not healthy: $PS"
printf '%s' "$PS" | grep -q 'app-'"$SLUG"'-console-1 .*healthy' \
  || fail "the console container is not healthy: $PS"
pass "both containers are \"healthy\""

# The proof that the password is not empty and that it is THE ONE the database
# was initialized with: we authenticate with it, from the container, without
# ever taking the value out.
AUTH=$(on_target "docker exec app-$SLUG-db-1 sh -c 'PGPASSWORD=\$POSTGRES_PASSWORD psql -h 127.0.0.1 -U verif -d verifdb -tAc \"select 42\"'" 2>&1 | tr -d ' \r')
[ "$AUTH" = "42" ] || fail "the database does not accept the .env's password: $AUTH"
pass "PostgreSQL authentication succeeded with the .env's value (select 42 → 42)"

if [ -n "$PORT" ]; then
  HTTP=$(curl -s -o "$WORK/app.html" -w '%{http_code}' "http://127.0.0.1:$PORT/" || true)
  [ "$HTTP" = "200" ] || info "the console answers HTTP $HTTP on 127.0.0.1:$PORT (not blocking)"
  [ "$HTTP" = "200" ] && pass "the exposed console answers HTTP 200 on 127.0.0.1:$PORT"
fi

step "8. The .env placed on the target carries a non-empty value"
RELEASE="$DRIVER_ROOT_PATH/apps/$SLUG/current"
ENV_MODE=$(on_target "stat -c %a $RELEASE/.env")
[ "$ENV_MODE" = "600" ] || fail ".env in mode $ENV_MODE, 600 expected"
pass ".env placed as 0600"

LEN=$(on_target "awk -F= '\$1==\"POSTGRES_PASSWORD\"{print length(\$0) - length(\$1) - 1}' $RELEASE/.env")
[ -n "$LEN" ] || fail "POSTGRES_PASSWORD missing from the .env"
[ "$LEN" -ge 16 ] || fail "POSTGRES_PASSWORD is $LEN character(s) long — it was exactly the original outage"
pass "POSTGRES_PASSWORD present, $LEN characters (never printed)"

on_target "grep -q '^CONSOLE_API_TOKEN=' $RELEASE/.env" \
  || fail "CONSOLE_API_TOKEN missing from the .env"
pass "CONSOLE_API_TOKEN, typed by the operator, is in the .env too"

# Fingerprint, not value: it is what will be compared after the redeployment.
FP1=$(on_target "grep '^POSTGRES_PASSWORD=' $RELEASE/.env | sha256sum | cut -c1-16")
info "secret's fingerprint (sha256, first 16 characters): $FP1"

step "9. The non-exposed database gets a TCP probe, not HTTP"
DB_PROBE=$(on_target "sed -n '/^  db:/,/^  console:/p' $RELEASE/compose.yml | grep -A2 'test:' | tr -d '\n'")
info "db probe: $(printf '%s' "$DB_PROBE" | sed 's/^ *//')"
printf '%s' "$DB_PROBE" | grep -q 'nc -z' || fail "the db probe is not an open-port test"
printf '%s' "$DB_PROBE" | grep -q 'dev/tcp' \
  || fail "the db probe does not fall back on /dev/tcp — unusable on a Debian image"
printf '%s' "$DB_PROBE" | grep -qE 'wget|curl|http://' \
  && fail "the db probe still contains an HTTP call"
pass "db: TCP probe (nc, then bash's /dev/tcp), no HTTP"

CONSOLE_PROBE=$(on_target "sed -n '/^  console:/,\$p' $RELEASE/compose.yml | grep -A2 'test:' | tr -d '\n'")
printf '%s' "$CONSOLE_PROBE" | grep -q 'http://127.0.0.1:8081/' \
  || fail "the exposed console should be probed over HTTP: $CONSOLE_PROBE"
pass "console: HTTP probe on the AppSpec's path"

on_target "grep -q 'service_healthy' $RELEASE/compose.yml" \
  || fail "depends_on: service_healthy missing — the blocking scenario is not reproduced"
pass "console waits for db as \"service_healthy\" — the condition that blocked"

step "10. A redeployment reuses the SAME secret"
D2=$(deploy)
req GET "/api/deployments/$D2" >/dev/null
STATUS=$(jq -r .status "$BODY")
[ "$STATUS" = "success" ] || fail "the redeployment ended as \"$STATUS\""
pass "redeployment $D2 succeeded"

FP2=$(on_target "grep '^POSTGRES_PASSWORD=' $RELEASE/.env | sha256sum | cut -c1-16")
[ "$FP1" = "$FP2" ] || fail "the secret changed at the redeployment ($FP1 → $FP2): the database would be unreachable"
pass "same fingerprint as at the first deployment: $FP2"

ROWS=$(psql_q "select count(*) from application_secrets where application_id = '$APP_ID' and name = 'POSTGRES_PASSWORD';")
[ "$ROWS" = "1" ] || fail "$ROWS row(s) for POSTGRES_PASSWORD, a single one expected"
pass "a single row in the database: the value is attached to the application, not to the deployment"

# The proof that matters: the database's volume survived, and the password it
# carries is still the .env's.
AUTH=$(on_target "docker exec app-$SLUG-db-1 sh -c 'PGPASSWORD=\$POSTGRES_PASSWORD psql -h 127.0.0.1 -U verif -d verifdb -tAc \"select 42\"'" 2>&1 | tr -d ' \r')
[ "$AUTH" = "42" ] || fail "after the redeployment, the database refuses the password: $AUTH"
pass "the database still answers — the existing volume recognizes the password"

step "11. The value comes out nowhere"
# Read here, and here only: the script needs it to look for leaks. It is never
# printed.
SECRET=$(on_target "grep '^POSTGRES_PASSWORD=' $RELEASE/.env | cut -d= -f2-")
[ -n "$SECRET" ] || fail "value unreadable on the target"

req GET "/api/applications/$APP_ID" >/dev/null
grep -qF "$SECRET" "$BODY" && fail "GET /api/applications/:id contains the value"
req GET "/api/applications/$APP_ID/secrets" >/dev/null
grep -qF "$SECRET" "$BODY" && fail "GET .../secrets contains the value"
req GET "/api/deployments/$D2" >/dev/null
grep -qF "$SECRET" "$BODY" && fail "the deployment exposes the value"
pass "no API response carries the value"

# The page lives in a drawer of /applications, rendered on the server, Secrets tab.
curl -s -b "$JAR" -c "$JAR" -H "origin: $BASE_URL" "$BASE_URL/applications?app=$APP_ID&tab=secrets" \
  -o "$WORK/page.html" -w '' || true
grep -qF "$SECRET" "$WORK/page.html" && fail "the HTML page contains the value"
grep -q 'Secrets' "$WORK/page.html" || info "\"Secrets\" section not found in the rendered HTML"
pass "the application's HTML page does not contain the value"

HITS=$(psql_q "select count(*) from audit_logs where coalesce(before::text,'') like '%$SECRET%' or coalesce(after::text,'') like '%$SECRET%';")
[ "$HITS" = "0" ] || fail "$HITS audit row(s) carry the value"
pass "audit_logs: no occurrence"

psql_q "select count(*) from audit_logs where action = 'application.secret.set' and resource_id = '$APP_ID';" \
  | grep -qv '^0$' || fail "the \"application.secret.set\" action was not logged"
pass "audit: application.secret.set logged (name and origin, without the value)"

for svc in panel worker; do
  # `grep -c` and not `grep -q`: under `set -o pipefail`, `grep -q` exits at the
  # first match, `docker compose logs` gets a SIGPIPE, and the pipe reports the
  # producer's failure. On a **negative** assertion like this one, this false
  # negative makes the check **pass** although a secret leaked — silence would
  # look like success. `grep -c` reads to the end.
    if [ "$(docker compose logs --no-log-prefix "$svc" 2>/dev/null | grep -cF "$SECRET")" != "0" ]; then
    fail "the value appears in \"docker compose logs $svc\""
  fi
done
pass "docker compose logs panel / worker: no occurrence"

# Nor the deployment logs, relayed over SSE then archived.
HITS=$(psql_q "select count(*) from deployment_steps where coalesce(log,'') like '%$SECRET%';" 2>/dev/null || echo 0)
[ "$HITS" = "0" ] || fail "$HITS deployment step(s) carry the value in their logs"
pass "step logs: no occurrence"

step "12. An unresolved secret makes the RENDERING fail, naming it"
req GET "/api/applications/$APP_ID" >/dev/null
jq -r '.appSpec' "$BODY" > "$WORK/appspec.json"

cat > "$WORK/render-check.mjs" <<'MJS'
import { readFileSync } from 'node:fs';

const { renderFiles } = await import(process.env.RENDER_MODULE);
const spec = JSON.parse(readFileSync(process.env.SPEC_FILE, 'utf8'));

// 1. No resolved value → the rendering must fail, and name the culprit.
let message = null;
try {
  renderFiles({ spec, appSlug: spec.name, publishedPort: null });
} catch (error) {
  message = error.message;
}
if (message === null) {
  console.error('NO_ERROR');
  process.exit(2);
}
if (!message.includes('POSTGRES_PASSWORD')) {
  console.error(`MESSAGE_WITHOUT_NAME: ${message}`);
  process.exit(3);
}
console.log(`THROWS ${message}`);

// 2. A DELIBERATELY empty secret stays legitimate: missing is not empty.
const values = {};
for (const service of spec.services) for (const name of service.secrets) values[name] = '';
const files = renderFiles({ spec, appSlug: spec.name, publishedPort: null, secretValues: values });
const env = files.find((file) => file.path === '.env');
if (!env || !/^POSTGRES_PASSWORD=$/m.test(env.content)) {
  console.error('EMPTY_REFUSED');
  process.exit(4);
}
console.log('EMPTY_ACCEPTED');
MJS

RENDER_MODULE="file://$ROOT/packages/core/dist/drivers/docker/render.js" \
SPEC_FILE="$WORK/appspec.json" \
  node "$WORK/render-check.mjs" > "$WORK/render.out" 2>"$WORK/render.err" \
  || fail "the rendering check failed: $(cat "$WORK/render.err")"

grep -q '^THROWS .*POSTGRES_PASSWORD' "$WORK/render.out" \
  || fail "the rendering did not fail naming POSTGRES_PASSWORD"
info "$(grep '^THROWS ' "$WORK/render.out" | cut -c8-)"
pass "a declared secret without a value makes the rendering fail, naming it"

grep -q '^EMPTY_ACCEPTED$' "$WORK/render.out" \
  || fail "a deliberately empty secret was refused"
pass "a deliberately empty secret stays accepted — missing is not empty"

step "13. The store is encrypted in the database"
STORED=$(psql_q "select encrypted_value from application_secrets where application_id = '$APP_ID' and name = 'POSTGRES_PASSWORD';")
printf '%s' "$STORED" | grep -q "^v1:" || fail "the encryption envelope is not in the \"v1:iv:tag:ciphertext\" format"
printf '%s' "$STORED" | grep -qF "$SECRET" && fail "the value in clear is readable in the database"
pass "stored as AES-256-GCM under MASTER_KEY, the same envelope as the SSH credentials"

# ═════════════════════════════════════════════════════════════════════════════
#  ALIASES — one password, two names
#
#  Everything above was about an AppSpec in bare strings: it just read back,
#  deployed, redeployed. It is the proof of backward compatibility, and it is
#  done. What follows adds `from`.
# ═════════════════════════════════════════════════════════════════════════════

step "14. Backward compatibility: the previous spec is indeed in bare strings"
req GET "/api/applications/$APP_ID" >/dev/null
jq -e '[.appSpec.services[].secrets[]] | all(type == "string")' "$BODY" >/dev/null \
  || fail "the first scenario's spec is no longer in bare strings — the proof is worth nothing"
pass "$(jq -rc '[.appSpec.services[].secrets[]] | unique' "$BODY"): bare strings, read back and deployed twice"

step "15. An alias is refused at VALIDATION when its target does not exist"
# The prompt's § 7.3 example, but the alias points next to it. The spec must
# never reach the database: it is `appSpecSchema` that refuses it, not the
# rendering.
mk_alias_spec() {
  local app_secret="$1"
  cat <<JSON
{
  "name": "$SLUG_ALIAS",
  "version": "1.0.0",
  "services": [
    {
      "name": "web",
      "source": { "type": "image", "ref": "wordpress:6-apache" },
      "port": 80,
      "exposed": true,
      "env": {
        "WORDPRESS_DB_HOST": "mariadb:3306",
        "WORDPRESS_DB_NAME": "verifdb",
        "WORDPRESS_DB_USER": "verif"
      },
      "secrets": [$app_secret],
      "resources": { "cpuMilli": 500, "memoryMi": 512 },
      "healthcheck": { "path": "/wp-admin/install.php", "intervalSec": 5, "timeoutSec": 5, "retries": 40 },
      "dependsOn": ["mariadb"]
    },
    {
      "name": "mariadb",
      "source": { "type": "image", "ref": "mariadb:11" },
      "port": 3306,
      "exposed": false,
      "env": { "MARIADB_DATABASE": "verifdb", "MARIADB_USER": "verif" },
      "secrets": ["MARIADB_PASSWORD", "MARIADB_ROOT_PASSWORD"],
      "resources": { "cpuMilli": 1000, "memoryMi": 1024 },
      "healthcheck": { "path": "/", "port": 3306, "intervalSec": 5, "timeoutSec": 3, "retries": 40 },
      "volumes": [{ "name": "donnees", "mountPath": "/var/lib/mysql", "size": "1Gi" }]
    }
  ]
}
JSON
}

mk_alias_spec '{ "name": "WORDPRESS_DB_PASSWORD", "from": "MOT_DE_PASSE_FANTOME" }' \
  | jq '{appSpec: .}' > "$WORK/ghost.json"
code=$(req POST /api/applications "@$WORK/ghost.json")
[ "$code" = "422" ] || fail "an AppSpec with a ghost alias was accepted (HTTP $code)"
grep -qF 'MOT_DE_PASSE_FANTOME' "$BODY" \
  || fail "the refusal does not name the missing secret: $(cat "$BODY")"
pass "alias to a non-existent secret → HTTP 422, and the message names it"
info "$(jq -r '[.error.details.fieldErrors.appSpec[]?] | join(" | ")' "$BODY" 2>/dev/null | cut -c1-160)"

ROWS=$(psql_q "select count(*) from applications where slug = '$SLUG_ALIAS';")
[ "$ROWS" = "0" ] || fail "the refused spec created an application all the same"
pass "nothing was written in the database: the refusal takes place before, not at deployment"

step "16. An alias cycle is refused too"
mk_alias_spec '{ "name": "WORDPRESS_DB_PASSWORD", "from": "MARIADB_PASSWORD" }' \
  | jq '(.services[1].secrets) = [{"name":"MARIADB_PASSWORD","from":"WORDPRESS_DB_PASSWORD"}, "MARIADB_ROOT_PASSWORD"] | {appSpec: .}' \
  > "$WORK/cycle.json"
code=$(req POST /api/applications "@$WORK/cycle.json")
[ "$code" = "422" ] || fail "an alias cycle was accepted (HTTP $code)"
grep -qE "cycle d'alias|alias cycle" "$BODY" || fail "the refusal does not speak of a cycle: $(cat "$BODY")"
pass "A ← B and B ← A → HTTP 422, \"secret alias cycle\""
info "$(jq -r '[.error.details.fieldErrors.appSpec[]?] | join(" | ")' "$BODY" 2>/dev/null | cut -c1-160)"

step "17. The prompt's canonical example, linked through \"from\" this time"
mk_alias_spec '{ "name": "WORDPRESS_DB_PASSWORD", "from": "MARIADB_PASSWORD" }' \
  | jq '{appSpec: .}' > "$WORK/alias.json"
code=$(req POST /api/applications "@$WORK/alias.json")
[ "$code" = "201" ] || fail "POST /api/applications → HTTP $code: $(cat "$BODY")"
ALIAS_APP_ID=$(jq -r .id "$BODY")
pass "application \"$SLUG_ALIAS\" created ($ALIAS_APP_ID)"

step "18. A single row in the database for both names"
ROWS=$(psql_q "select count(*) from application_secrets where application_id = '$ALIAS_APP_ID';")
[ "$ROWS" = "2" ] || fail "$ROWS row(s) in the database, 2 expected (MARIADB_PASSWORD and MARIADB_ROOT_PASSWORD)"
NAMES=$(psql_q "select name from application_secrets where application_id = '$ALIAS_APP_ID' order by name;" | tr '\n' ' ')
pass "rows in the database: $NAMES"
ROWS=$(psql_q "select count(*) from application_secrets where application_id = '$ALIAS_APP_ID' and name = 'WORDPRESS_DB_PASSWORD';")
[ "$ROWS" = "0" ] || fail "the WORDPRESS_DB_PASSWORD alias has its own row: it is the original outage with one more step"
pass "WORDPRESS_DB_PASSWORD has NO row: there is only one secret, read under two names"

step "19. The secrets screen says that a name is an alias"
code=$(req GET "/api/applications/$ALIAS_APP_ID/secrets")
[ "$code" = "200" ] || fail "GET .../secrets → HTTP $code"
jq -e '.items[] | select(.name == "WORDPRESS_DB_PASSWORD") | .aliasOf == "MARIADB_PASSWORD"' "$BODY" >/dev/null \
  || fail "the API does not flag WORDPRESS_DB_PASSWORD as an alias: $(jq -c '.items' "$BODY")"
jq -e '.items[] | select(.name == "WORDPRESS_DB_PASSWORD") | .isSet == true' "$BODY" >/dev/null \
  || fail "the alias is shown as without a value — the screen would invite setting one"
jq -e '.items[] | select(.name == "MARIADB_PASSWORD") | .readAs == ["WORDPRESS_DB_PASSWORD"]' "$BODY" >/dev/null \
  || fail "MARIADB_PASSWORD does not say it is read under another name"
pass "$(jq -rc '[.items[] | "\(.name)\(if .aliasOf then " ← " + .aliasOf else "" end)"] | join(", ")' "$BODY")"

# Setting a value on the alias would create the second row. It is refused.
code=$(req PUT "/api/applications/$ALIAS_APP_ID/secrets/WORDPRESS_DB_PASSWORD" '{"generate":true}')
[ "$code" = "409" ] || fail "the API accepted setting a value on an alias (HTTP $code)"
grep -qF 'MARIADB_PASSWORD' "$BODY" || fail "the refusal does not point to the secret that carries the value"
pass "PUT on an alias → HTTP 409, pointed to \"MARIADB_PASSWORD\""

step "20. Deployment: MariaDB starts, WordPress connects to it"
DA=$(deploy "$ALIAS_APP_ID")
req GET "/api/deployments/$DA" >/dev/null
STATUS=$(jq -r .status "$BODY")
[ "$STATUS" = "success" ] || {
  info "steps: $(jq -rc '[.steps[] | "\(.key)=\(.status)"] | join(" ")' "$BODY")"
  info "error: $(jq -r '.error // "(none)"' "$BODY")"
  fail "the deployment of \"$SLUG_ALIAS\" ended as \"$STATUS\""
}
ALIAS_PORT=$(jq -r '.publishedPort // empty' "$BODY")
pass "deployment $DA succeeded — published port $ALIAS_PORT"

PS=$(on_target "docker ps --filter label=tp.app=$SLUG_ALIAS --format '{{.Names}} {{.Status}}'")
printf '%s\n' "$PS" | while IFS= read -r line; do [ -n "$line" ] && info "$line"; done
printf '%s' "$PS" | grep -q 'app-'"$SLUG_ALIAS"'-mariadb-1 .*healthy' \
  || fail "MariaDB is not healthy: $PS"
pass "MariaDB is \"healthy\" — MARIADB_ROOT_PASSWORD let it initialize"

# The proof that matters. `healthy` on WordPress means /wp-admin/install.php
# answered 200; on a refused connection, this page returns a 500 "Error
# establishing a database connection". So it is indeed the MySQL
# authentication that succeeded, not a container that runs.
printf '%s' "$PS" | grep -q 'app-'"$SLUG_ALIAS"'-web-1 .*healthy' \
  || fail "WordPress is not healthy: it could not reach its database — $PS"
pass "WordPress is \"healthy\": /wp-admin/install.php answers 200, so the database authenticated it"

# And we ask again explicitly, from the target, without going through the probe.
INSTALL=$(on_target "docker exec app-$SLUG_ALIAS-web-1 curl -s -o /dev/null -w '%{http_code}' http://127.0.0.1/wp-admin/install.php")
[ "$INSTALL" = "200" ] || fail "/wp-admin/install.php answers $INSTALL — the connection to the database failed"
pass "GET /wp-admin/install.php → 200 (a refused connection would return 500)"

# Last proof, on the database side: the application account accepts the
# password it received through the alias. We use it, we do not print it.
AUTH=$(on_target "docker exec app-$SLUG_ALIAS-mariadb-1 sh -c 'mariadb -h 127.0.0.1 -u verif -p\"\$MARIADB_PASSWORD\" -D verifdb -N -B -e \"select 42\"'" 2>&1 | tr -d ' \r')
[ "$AUTH" = "42" ] || fail "MariaDB refuses the application account's password: $AUTH"
pass "MariaDB authentication succeeded with the .env's value (select 42 → 42)"

ERRORS=$(on_target "docker logs app-$SLUG_ALIAS-mariadb-1 2>&1 | grep -c 'Access denied' || true")
[ "$ERRORS" = "0" ] || fail "$ERRORS authentication refusals in MariaDB's logs — the two names do not carry the same value"
pass "no \"Access denied\" in MariaDB's logs"

step "21. Both names carry the SAME value in the placed .env"
ALIAS_RELEASE="$DRIVER_ROOT_PATH/apps/$SLUG_ALIAS/current"
on_target "test -d $ALIAS_RELEASE" 2>/dev/null || ALIAS_RELEASE="$DRIVER_ROOT_PATH/apps/$SLUG_ALIAS/1.0.0"
FP_APP=$(on_target "grep '^WORDPRESS_DB_PASSWORD=' $ALIAS_RELEASE/.env | cut -d= -f2- | sha256sum | cut -c1-16")
FP_DB=$(on_target "grep '^MARIADB_PASSWORD=' $ALIAS_RELEASE/.env | cut -d= -f2- | sha256sum | cut -c1-16")
FP_ROOT=$(on_target "grep '^MARIADB_ROOT_PASSWORD=' $ALIAS_RELEASE/.env | cut -d= -f2- | sha256sum | cut -c1-16")
[ -n "$FP_APP" ] || fail "WORDPRESS_DB_PASSWORD missing from the .env — the alias produced nothing"
info "WORDPRESS_DB_PASSWORD  sha256[0:16] = $FP_APP"
info "MARIADB_PASSWORD       sha256[0:16] = $FP_DB"
info "MARIADB_ROOT_PASSWORD  sha256[0:16] = $FP_ROOT"
[ "$FP_APP" = "$FP_DB" ] || fail "the two names carry DIFFERENT values ($FP_APP ≠ $FP_DB): it is the original outage"
pass "same fingerprint on both sides: a single value, read under two names"
[ "$FP_ROOT" != "$FP_DB" ] || fail "the root password is the same as the application's — they are two distinct secrets"
pass "MARIADB_ROOT_PASSWORD is indeed a SECOND secret, not an alias of the first"

step "22. A redeployment changes nothing"
DA2=$(deploy "$ALIAS_APP_ID")
req GET "/api/deployments/$DA2" >/dev/null
[ "$(jq -r .status "$BODY")" = "success" ] || fail "the redeployment of \"$SLUG_ALIAS\" failed"
FP_APP2=$(on_target "grep '^WORDPRESS_DB_PASSWORD=' $ALIAS_RELEASE/.env | cut -d= -f2- | sha256sum | cut -c1-16")
[ "$FP_APP2" = "$FP_APP" ] || fail "the alias changed value at the redeployment ($FP_APP → $FP_APP2)"
pass "redeployment $DA2: same fingerprint, and the MariaDB volume still recognizes the account"
AUTH=$(on_target "docker exec app-$SLUG_ALIAS-mariadb-1 sh -c 'mariadb -h 127.0.0.1 -u verif -p\"\$MARIADB_PASSWORD\" -D verifdb -N -B -e \"select 42\"'" 2>&1 | tr -d ' \r')
[ "$AUTH" = "42" ] || fail "after the redeployment, MariaDB refuses the password: $AUTH"
pass "authentication still good after the redeployment"

step "23. The K3s rendering gets the same map as the Docker rendering"
# The question this check settles: is the alias resolved BEFORE the rendering,
# in the neutral code? If the resolution went through Compose's `.env` `${…}`
# interpolation, Kubernetes — which interpolates nothing — would get a truncated
# Secret, and the same AppSpec would work on one runtime and not the other.
req GET "/api/applications/$ALIAS_APP_ID" >/dev/null
jq -r '.appSpec' "$BODY" > "$WORK/alias-spec.json"

cat > "$WORK/parity.mjs" <<'MJS'
import { readFileSync } from 'node:fs';
import { createHash } from 'node:crypto';

const docker = await import(`${process.env.DIST}/drivers/docker/render.js`);
const k3s = await import(`${process.env.DIST}/drivers/k3s/render.js`);
const { storedSecretNames } = await import(`${process.env.DIST}/spec/index.js`);
const spec = JSON.parse(readFileSync(process.env.SPEC_FILE, 'utf8'));

// What the driver would ask the store for: the roots only.
const roots = storedSecretNames(spec);
console.log(`ROOTS ${roots.sort().join(',')}`);

const secretValues = Object.fromEntries(roots.map((name) => [name, `value-of-${name}`]));

const env = docker
  .renderFiles({ spec, appSlug: spec.name, publishedPort: null, secretValues })
  .find((file) => file.path === '.env');
const composeMap = Object.fromEntries(
  env.content.trim().split('\n').map((line) => {
    const at = line.indexOf('=');
    return [line.slice(0, at), line.slice(at + 1)];
  }),
);

const kubeMap = {};
for (const manifest of k3s.renderManifests({ spec, appSlug: spec.name, secretValues })) {
  if (manifest.kind !== 'Secret') continue;
  Object.assign(kubeMap, manifest.stringData);
}

const digest = (map) =>
  createHash('sha256')
    .update(JSON.stringify(Object.entries(map).sort()))
    .digest('hex')
    .slice(0, 16);

console.log(`COMPOSE ${Object.keys(composeMap).sort().join(',')} ${digest(composeMap)}`);
console.log(`KUBE    ${Object.keys(kubeMap).sort().join(',')} ${digest(kubeMap)}`);
if (digest(composeMap) !== digest(kubeMap)) {
  console.error('MAPS_DIFFER');
  process.exit(2);
}
if (composeMap.WORDPRESS_DB_PASSWORD !== composeMap.MARIADB_PASSWORD) {
  console.error('ALIAS_UNRESOLVED_DOCKER');
  process.exit(3);
}
if (kubeMap.WORDPRESS_DB_PASSWORD !== kubeMap.MARIADB_PASSWORD) {
  console.error('ALIAS_UNRESOLVED_K3S');
  process.exit(4);
}
// No interpolation must remain: a complete map, not a reference.
if (/\$\{/.test(env.content)) {
  console.error('INTERPOLATION_IN_ENV');
  process.exit(5);
}
console.log('PARITY_OK');
MJS

DIST="file://$ROOT/packages/core/dist" SPEC_FILE="$WORK/alias-spec.json" \
  node "$WORK/parity.mjs" > "$WORK/parity.out" 2>"$WORK/parity.err" \
  || fail "the parity check failed: $(cat "$WORK/parity.err") $(cat "$WORK/parity.out")"

info "$(grep '^ROOTS ' "$WORK/parity.out")"
info "$(grep '^COMPOSE ' "$WORK/parity.out")"
info "$(grep '^KUBE' "$WORK/parity.out")"
grep -q '^PARITY_OK$' "$WORK/parity.out" || fail "the two renderings do not get the same map"
pass "Docker and K3s get the same complete map, alias resolved, without interpolation"

printf '\n\033[32m✓ Secrets store, aliases and probe rule verified.\033[0m\n'
printf '\033[2m  Screens: %s/applications/%s\033[0m\n' "$BASE_URL" "$APP_ID"
printf '\033[2m           %s/applications/%s\033[0m\n' "$BASE_URL" "$ALIAS_APP_ID"
