// Generated by `pnpm --filter @pupitre/web routes:table` — do not edit by hand.
import 'server-only';
import * as route_account_avatar from '@/app/api/account/avatar/route';
import * as route_account_password from '@/app/api/account/password/route';
import * as route_account_sessions from '@/app/api/account/sessions/route';
import * as route_account_sessions_$id from '@/app/api/account/sessions/[id]/route';
import * as route_account_sessions_revoke_others from '@/app/api/account/sessions/revoke-others/route';
import * as route_account_two_factor_activate from '@/app/api/account/two-factor/activate/route';
import * as route_account_two_factor_disable from '@/app/api/account/two-factor/disable/route';
import * as route_account_two_factor_setup from '@/app/api/account/two-factor/setup/route';
import * as route_admin_roles from '@/app/api/admin/roles/route';
import * as route_admin_roles_$key from '@/app/api/admin/roles/[key]/route';
import * as route_admin_tokens from '@/app/api/admin/tokens/route';
import * as route_admin_users from '@/app/api/admin/users/route';
import * as route_admin_users_$id from '@/app/api/admin/users/[id]/route';
import * as route_admin_users_$id_avatar from '@/app/api/admin/users/[id]/avatar/route';
import * as route_admin_users_$id_invitation from '@/app/api/admin/users/[id]/invitation/route';
import * as route_admin_users_$id_role from '@/app/api/admin/users/[id]/role/route';
import * as route_admin_users_$id_status from '@/app/api/admin/users/[id]/status/route';
import * as route_admin_users_$id_two_factor from '@/app/api/admin/users/[id]/two-factor/route';
import * as route_applications from '@/app/api/applications/route';
import * as route_applications_$id from '@/app/api/applications/[id]/route';
import * as route_applications_$id_archives from '@/app/api/applications/[id]/archives/route';
import * as route_applications_$id_archives_$archiveId from '@/app/api/applications/[id]/archives/[archiveId]/route';
import * as route_applications_$id_backup_policy from '@/app/api/applications/[id]/backup-policy/route';
import * as route_applications_$id_backups from '@/app/api/applications/[id]/backups/route';
import * as route_applications_$id_cascade from '@/app/api/applications/[id]/cascade/route';
import * as route_applications_$id_images from '@/app/api/applications/[id]/images/route';
import * as route_applications_$id_images_check from '@/app/api/applications/[id]/images/check/route';
import * as route_applications_$id_redeploy from '@/app/api/applications/[id]/redeploy/route';
import * as route_applications_$id_routes from '@/app/api/applications/[id]/routes/route';
import * as route_applications_$id_scan_policy from '@/app/api/applications/[id]/scan-policy/route';
import * as route_applications_$id_secrets from '@/app/api/applications/[id]/secrets/route';
import * as route_applications_$id_secrets_$name from '@/app/api/applications/[id]/secrets/[name]/route';
import * as route_applications_$id_sources from '@/app/api/applications/[id]/sources/route';
import * as route_applications_$id_sources_$sourceId from '@/app/api/applications/[id]/sources/[sourceId]/route';
import * as route_applications_$id_sources_$sourceId_check from '@/app/api/applications/[id]/sources/[sourceId]/check/route';
import * as route_applications_$id_sources_$sourceId_deploy from '@/app/api/applications/[id]/sources/[sourceId]/deploy/route';
import * as route_applications_$id_versions from '@/app/api/applications/[id]/versions/route';
import * as route_applications_$id_vulnerability_acceptances from '@/app/api/applications/[id]/vulnerability-acceptances/route';
import * as route_applications_$id_vulnerability_acceptances_$acceptanceId from '@/app/api/applications/[id]/vulnerability-acceptances/[acceptanceId]/route';
import * as route_applications_from_source from '@/app/api/applications/from-source/route';
import * as route_applications_generate from '@/app/api/applications/generate/route';
import * as route_applications_import_compose from '@/app/api/applications/import-compose/route';
import * as route_apps from '@/app/api/apps/route';
import * as route_apps_$id_logs from '@/app/api/apps/[id]/logs/route';
import * as route_apps_$id_restart from '@/app/api/apps/[id]/restart/route';
import * as route_apps_$id_start from '@/app/api/apps/[id]/start/route';
import * as route_apps_$id_state from '@/app/api/apps/[id]/state/route';
import * as route_apps_$id_stop from '@/app/api/apps/[id]/stop/route';
import * as route_appspec_schema from '@/app/api/appspec/schema/route';
import * as route_appspec_validate from '@/app/api/appspec/validate/route';
import * as route_audit_logs from '@/app/api/audit-logs/route';
import * as route_audit_logs_export from '@/app/api/audit-logs/export/route';
import * as route_backups_$id from '@/app/api/backups/[id]/route';
import * as route_backups_$id_restore from '@/app/api/backups/[id]/restore/route';
import * as route_backups_destination from '@/app/api/backups/destination/route';
import * as route_backups_destination_check from '@/app/api/backups/destination/check/route';
import * as route_backups_panel from '@/app/api/backups/panel/route';
import * as route_backups_panel_schedule from '@/app/api/backups/panel/schedule/route';
import * as route_catalog_$id from '@/app/api/catalog/[id]/route';
import * as route_chat_attachments_$id from '@/app/api/chat/attachments/[id]/route';
import * as route_chat_directory from '@/app/api/chat/directory/route';
import * as route_chat_messages from '@/app/api/chat/messages/route';
import * as route_chat_messages_$id from '@/app/api/chat/messages/[id]/route';
import * as route_chat_messages_$id_reactions from '@/app/api/chat/messages/[id]/reactions/route';
import * as route_chat_read from '@/app/api/chat/read/route';
import * as route_deployments from '@/app/api/deployments/route';
import * as route_deployments_$id from '@/app/api/deployments/[id]/route';
import * as route_deployments_$id_logs from '@/app/api/deployments/[id]/logs/route';
import * as route_deployments_$id_logs_export from '@/app/api/deployments/[id]/logs/export/route';
import * as route_deployments_$id_purge from '@/app/api/deployments/[id]/purge/route';
import * as route_deployments_$id_rollback from '@/app/api/deployments/[id]/rollback/route';
import * as route_deployments_$id_scans from '@/app/api/deployments/[id]/scans/route';
import * as route_deployments_$id_unblock from '@/app/api/deployments/[id]/unblock/route';
import * as route_deployments_export from '@/app/api/deployments/export/route';
import * as route_deployments_purge from '@/app/api/deployments/purge/route';
import * as route_deployments_stuck from '@/app/api/deployments/stuck/route';
import * as route_domains from '@/app/api/domains/route';
import * as route_domains_$id_inspect from '@/app/api/domains/[id]/inspect/route';
import * as route_findings from '@/app/api/findings/route';
import * as route_forecasts from '@/app/api/forecasts/route';
import * as route_health from '@/app/api/health/route';
import * as route_integrations_gitea from '@/app/api/integrations/gitea/route';
import * as route_integrations_gitea_check from '@/app/api/integrations/gitea/check/route';
import * as route_integrations_github from '@/app/api/integrations/github/route';
import * as route_integrations_github_manifest from '@/app/api/integrations/github/manifest/route';
import * as route_integrations_gitlab from '@/app/api/integrations/gitlab/route';
import * as route_integrations_gitlab_check from '@/app/api/integrations/gitlab/check/route';
import * as route_integrations_repositories from '@/app/api/integrations/repositories/route';
import * as route_integrations_specs from '@/app/api/integrations/specs/route';
import * as route_jobs from '@/app/api/jobs/route';
import * as route_jobs_$id from '@/app/api/jobs/[id]/route';
import * as route_jobs_$id_run from '@/app/api/jobs/[id]/run/route';
import * as route_maintenance_windows from '@/app/api/maintenance-windows/route';
import * as route_maintenance_windows_$id from '@/app/api/maintenance-windows/[id]/route';
import * as route_me from '@/app/api/me/route';
import * as route_monitors from '@/app/api/monitors/route';
import * as route_monitors_$id from '@/app/api/monitors/[id]/route';
import * as route_monitors_$id_captures_$captureId from '@/app/api/monitors/[id]/captures/[captureId]/route';
import * as route_monitors_$id_check from '@/app/api/monitors/[id]/check/route';
import * as route_notifications_channels from '@/app/api/notifications/channels/route';
import * as route_notifications_channels_$id from '@/app/api/notifications/channels/[id]/route';
import * as route_notifications_channels_$id_test from '@/app/api/notifications/channels/[id]/test/route';
import * as route_notifications_digests from '@/app/api/notifications/digests/route';
import * as route_onboarding from '@/app/api/onboarding/route';
import * as route_ping from '@/app/api/ping/route';
import * as route_ping_$id from '@/app/api/ping/[id]/route';
import * as route_presence from '@/app/api/presence/route';
import * as route_proxies from '@/app/api/proxies/route';
import * as route_proxies_$id from '@/app/api/proxies/[id]/route';
import * as route_proxies_$id_check from '@/app/api/proxies/[id]/check/route';
import * as route_queue_jobs_$id from '@/app/api/queue/jobs/[id]/route';
import * as route_scans_$id from '@/app/api/scans/[id]/route';
import * as route_scans_$id_sbom from '@/app/api/scans/[id]/sbom/route';
import * as route_search from '@/app/api/search/route';
import * as route_settings from '@/app/api/settings/route';
import * as route_settings_sso_check from '@/app/api/settings/sso/check/route';
import * as route_source_proposals_$id_approve from '@/app/api/source-proposals/[id]/approve/route';
import * as route_source_proposals_$id_dismiss from '@/app/api/source-proposals/[id]/dismiss/route';
import * as route_status_pages from '@/app/api/status-pages/route';
import * as route_status_pages_$id from '@/app/api/status-pages/[id]/route';
import * as route_status_pages_preview from '@/app/api/status-pages/preview/route';
import * as route_status_updates from '@/app/api/status-updates/route';
import * as route_status_updates_$id from '@/app/api/status-updates/[id]/route';
import * as route_supervision_thresholds from '@/app/api/supervision/thresholds/route';
import * as route_targets from '@/app/api/targets/route';
import * as route_targets_$id from '@/app/api/targets/[id]/route';
import * as route_targets_$id_dns from '@/app/api/targets/[id]/dns/route';
import * as route_targets_$id_host_key from '@/app/api/targets/[id]/host-key/route';
import * as route_targets_$id_metrics from '@/app/api/targets/[id]/metrics/route';
import * as route_targets_$id_metrics_history from '@/app/api/targets/[id]/metrics/history/route';
import * as route_targets_$id_ports from '@/app/api/targets/[id]/ports/route';
import * as route_targets_$id_preflight from '@/app/api/targets/[id]/preflight/route';
import * as route_targets_$id_proxy from '@/app/api/targets/[id]/proxy/route';
import * as route_targets_$id_proxy_check from '@/app/api/targets/[id]/proxy/check/route';
import * as route_targets_$id_proxy_detect from '@/app/api/targets/[id]/proxy/detect/route';
import * as route_targets_$id_proxy_install from '@/app/api/targets/[id]/proxy/install/route';
import * as route_targets_$id_proxy_link from '@/app/api/targets/[id]/proxy/link/route';
import * as route_targets_$id_proxy_link_check from '@/app/api/targets/[id]/proxy/link/check/route';
import * as route_targets_$id_workloads from '@/app/api/targets/[id]/workloads/route';
import * as route_targets_$id_workloads_$ref from '@/app/api/targets/[id]/workloads/[ref]/route';
import * as route_targets_$id_workloads_$ref_control from '@/app/api/targets/[id]/workloads/[ref]/control/route';
import * as route_targets_$id_workloads_$ref_exec from '@/app/api/targets/[id]/workloads/[ref]/exec/route';
import * as route_targets_$id_workloads_$ref_logs from '@/app/api/targets/[id]/workloads/[ref]/logs/route';
import * as route_targets_$id_workloads_$ref_update from '@/app/api/targets/[id]/workloads/[ref]/update/route';
import * as route_targets_$id_workloads_events from '@/app/api/targets/[id]/workloads/events/route';
import * as route_tokens from '@/app/api/tokens/route';
import * as route_tokens_$id from '@/app/api/tokens/[id]/route';
import * as route_users_$id_avatar from '@/app/api/users/[id]/avatar/route';

/**
 * Every Route Handler the MCP endpoint can reach, by its pattern. Those set aside
 * are listed in `scripts/route-table.mjs`, with the reason.
 */
export const ROUTE_MODULES: Record<string, object> = {
  '/api/account/avatar': route_account_avatar,
  '/api/account/password': route_account_password,
  '/api/account/sessions': route_account_sessions,
  '/api/account/sessions/[id]': route_account_sessions_$id,
  '/api/account/sessions/revoke-others': route_account_sessions_revoke_others,
  '/api/account/two-factor/activate': route_account_two_factor_activate,
  '/api/account/two-factor/disable': route_account_two_factor_disable,
  '/api/account/two-factor/setup': route_account_two_factor_setup,
  '/api/admin/roles': route_admin_roles,
  '/api/admin/roles/[key]': route_admin_roles_$key,
  '/api/admin/tokens': route_admin_tokens,
  '/api/admin/users': route_admin_users,
  '/api/admin/users/[id]': route_admin_users_$id,
  '/api/admin/users/[id]/avatar': route_admin_users_$id_avatar,
  '/api/admin/users/[id]/invitation': route_admin_users_$id_invitation,
  '/api/admin/users/[id]/role': route_admin_users_$id_role,
  '/api/admin/users/[id]/status': route_admin_users_$id_status,
  '/api/admin/users/[id]/two-factor': route_admin_users_$id_two_factor,
  '/api/applications': route_applications,
  '/api/applications/[id]': route_applications_$id,
  '/api/applications/[id]/archives': route_applications_$id_archives,
  '/api/applications/[id]/archives/[archiveId]': route_applications_$id_archives_$archiveId,
  '/api/applications/[id]/backup-policy': route_applications_$id_backup_policy,
  '/api/applications/[id]/backups': route_applications_$id_backups,
  '/api/applications/[id]/cascade': route_applications_$id_cascade,
  '/api/applications/[id]/images': route_applications_$id_images,
  '/api/applications/[id]/images/check': route_applications_$id_images_check,
  '/api/applications/[id]/redeploy': route_applications_$id_redeploy,
  '/api/applications/[id]/routes': route_applications_$id_routes,
  '/api/applications/[id]/scan-policy': route_applications_$id_scan_policy,
  '/api/applications/[id]/secrets': route_applications_$id_secrets,
  '/api/applications/[id]/secrets/[name]': route_applications_$id_secrets_$name,
  '/api/applications/[id]/sources': route_applications_$id_sources,
  '/api/applications/[id]/sources/[sourceId]': route_applications_$id_sources_$sourceId,
  '/api/applications/[id]/sources/[sourceId]/check': route_applications_$id_sources_$sourceId_check,
  '/api/applications/[id]/sources/[sourceId]/deploy': route_applications_$id_sources_$sourceId_deploy,
  '/api/applications/[id]/versions': route_applications_$id_versions,
  '/api/applications/[id]/vulnerability-acceptances': route_applications_$id_vulnerability_acceptances,
  '/api/applications/[id]/vulnerability-acceptances/[acceptanceId]': route_applications_$id_vulnerability_acceptances_$acceptanceId,
  '/api/applications/from-source': route_applications_from_source,
  '/api/applications/generate': route_applications_generate,
  '/api/applications/import-compose': route_applications_import_compose,
  '/api/apps': route_apps,
  '/api/apps/[id]/logs': route_apps_$id_logs,
  '/api/apps/[id]/restart': route_apps_$id_restart,
  '/api/apps/[id]/start': route_apps_$id_start,
  '/api/apps/[id]/state': route_apps_$id_state,
  '/api/apps/[id]/stop': route_apps_$id_stop,
  '/api/appspec/schema': route_appspec_schema,
  '/api/appspec/validate': route_appspec_validate,
  '/api/audit-logs': route_audit_logs,
  '/api/audit-logs/export': route_audit_logs_export,
  '/api/backups/[id]': route_backups_$id,
  '/api/backups/[id]/restore': route_backups_$id_restore,
  '/api/backups/destination': route_backups_destination,
  '/api/backups/destination/check': route_backups_destination_check,
  '/api/backups/panel': route_backups_panel,
  '/api/backups/panel/schedule': route_backups_panel_schedule,
  '/api/catalog/[id]': route_catalog_$id,
  '/api/chat/attachments/[id]': route_chat_attachments_$id,
  '/api/chat/directory': route_chat_directory,
  '/api/chat/messages': route_chat_messages,
  '/api/chat/messages/[id]': route_chat_messages_$id,
  '/api/chat/messages/[id]/reactions': route_chat_messages_$id_reactions,
  '/api/chat/read': route_chat_read,
  '/api/deployments': route_deployments,
  '/api/deployments/[id]': route_deployments_$id,
  '/api/deployments/[id]/logs': route_deployments_$id_logs,
  '/api/deployments/[id]/logs/export': route_deployments_$id_logs_export,
  '/api/deployments/[id]/purge': route_deployments_$id_purge,
  '/api/deployments/[id]/rollback': route_deployments_$id_rollback,
  '/api/deployments/[id]/scans': route_deployments_$id_scans,
  '/api/deployments/[id]/unblock': route_deployments_$id_unblock,
  '/api/deployments/export': route_deployments_export,
  '/api/deployments/purge': route_deployments_purge,
  '/api/deployments/stuck': route_deployments_stuck,
  '/api/domains': route_domains,
  '/api/domains/[id]/inspect': route_domains_$id_inspect,
  '/api/findings': route_findings,
  '/api/forecasts': route_forecasts,
  '/api/health': route_health,
  '/api/integrations/gitea': route_integrations_gitea,
  '/api/integrations/gitea/check': route_integrations_gitea_check,
  '/api/integrations/github': route_integrations_github,
  '/api/integrations/github/manifest': route_integrations_github_manifest,
  '/api/integrations/gitlab': route_integrations_gitlab,
  '/api/integrations/gitlab/check': route_integrations_gitlab_check,
  '/api/integrations/repositories': route_integrations_repositories,
  '/api/integrations/specs': route_integrations_specs,
  '/api/jobs': route_jobs,
  '/api/jobs/[id]': route_jobs_$id,
  '/api/jobs/[id]/run': route_jobs_$id_run,
  '/api/maintenance-windows': route_maintenance_windows,
  '/api/maintenance-windows/[id]': route_maintenance_windows_$id,
  '/api/me': route_me,
  '/api/monitors': route_monitors,
  '/api/monitors/[id]': route_monitors_$id,
  '/api/monitors/[id]/captures/[captureId]': route_monitors_$id_captures_$captureId,
  '/api/monitors/[id]/check': route_monitors_$id_check,
  '/api/notifications/channels': route_notifications_channels,
  '/api/notifications/channels/[id]': route_notifications_channels_$id,
  '/api/notifications/channels/[id]/test': route_notifications_channels_$id_test,
  '/api/notifications/digests': route_notifications_digests,
  '/api/onboarding': route_onboarding,
  '/api/ping': route_ping,
  '/api/ping/[id]': route_ping_$id,
  '/api/presence': route_presence,
  '/api/proxies': route_proxies,
  '/api/proxies/[id]': route_proxies_$id,
  '/api/proxies/[id]/check': route_proxies_$id_check,
  '/api/queue/jobs/[id]': route_queue_jobs_$id,
  '/api/scans/[id]': route_scans_$id,
  '/api/scans/[id]/sbom': route_scans_$id_sbom,
  '/api/search': route_search,
  '/api/settings': route_settings,
  '/api/settings/sso/check': route_settings_sso_check,
  '/api/source-proposals/[id]/approve': route_source_proposals_$id_approve,
  '/api/source-proposals/[id]/dismiss': route_source_proposals_$id_dismiss,
  '/api/status-pages': route_status_pages,
  '/api/status-pages/[id]': route_status_pages_$id,
  '/api/status-pages/preview': route_status_pages_preview,
  '/api/status-updates': route_status_updates,
  '/api/status-updates/[id]': route_status_updates_$id,
  '/api/supervision/thresholds': route_supervision_thresholds,
  '/api/targets': route_targets,
  '/api/targets/[id]': route_targets_$id,
  '/api/targets/[id]/dns': route_targets_$id_dns,
  '/api/targets/[id]/host-key': route_targets_$id_host_key,
  '/api/targets/[id]/metrics': route_targets_$id_metrics,
  '/api/targets/[id]/metrics/history': route_targets_$id_metrics_history,
  '/api/targets/[id]/ports': route_targets_$id_ports,
  '/api/targets/[id]/preflight': route_targets_$id_preflight,
  '/api/targets/[id]/proxy': route_targets_$id_proxy,
  '/api/targets/[id]/proxy/check': route_targets_$id_proxy_check,
  '/api/targets/[id]/proxy/detect': route_targets_$id_proxy_detect,
  '/api/targets/[id]/proxy/install': route_targets_$id_proxy_install,
  '/api/targets/[id]/proxy/link': route_targets_$id_proxy_link,
  '/api/targets/[id]/proxy/link/check': route_targets_$id_proxy_link_check,
  '/api/targets/[id]/workloads': route_targets_$id_workloads,
  '/api/targets/[id]/workloads/[ref]': route_targets_$id_workloads_$ref,
  '/api/targets/[id]/workloads/[ref]/control': route_targets_$id_workloads_$ref_control,
  '/api/targets/[id]/workloads/[ref]/exec': route_targets_$id_workloads_$ref_exec,
  '/api/targets/[id]/workloads/[ref]/logs': route_targets_$id_workloads_$ref_logs,
  '/api/targets/[id]/workloads/[ref]/update': route_targets_$id_workloads_$ref_update,
  '/api/targets/[id]/workloads/events': route_targets_$id_workloads_events,
  '/api/tokens': route_tokens,
  '/api/tokens/[id]': route_tokens_$id,
  '/api/users/[id]/avatar': route_users_$id_avatar,
};
